extends:
  - '@commitlint/config-conventional'
rules:
  header-max-length: [1, 'always', 80]
  type-enum:
    - 2
    - always
    - - ci
      - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - revert
      - chore
  scope-enum:
    - 2
    - always
    - - general
      - core
      - socket
      - types
      - changePrefix
      - current
      - disconnect
      - help
      - lyrics
      - pause
      - play
      - remove
      - resume
      - skip
      - stop
      - loop
      - shuffle
      - autoplay
      - move
      - settings
      - dj
      - volume
      - queue
  subject-case:
    - 2
    - always
    - 'sentence-case'
