name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Delete gh-pages branch
        uses: dawidd6/action-delete-branch@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: gh-pages

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: |
          npm install
          npx @docusaurus/init@next init docusaurus classic
          cd ./packages/vocality-core
          rm -rf ../../docusaurus/docs
          npm run docs
          cd ../../docusaurus
          rm sidebars.js 
          cp ./website/sidebars.js ./
          rm docusaurus.config.js
          cp ../.docusaurus/docusaurus.config.js ./
          sed -i "26i apiKey: '${{ secrets.ALGOLIA_API_KEY }}'," ./docusaurus.config.js
          rm ./static/img/favicon.ico
          cp ../media/favicon.ico ./static/img/
          rm ./static/img/logo.svg
          cp ../media/logo.svg ./static/img/ 
          rm ./src/pages/index.js
          cp ../.docusaurus/index.js ./src/pages/index.js
          rm ./src/css/custom.css
          cp ../.docusaurus/custom.css ./src/css/custom.css
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docusaurus/build
