name: Documentation

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        uses: actions/setup-node@v1
          with:
          node-version: 12

      - run: npm install
      - run: cd ./packages/vocality-core
      - run: npm run docs

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: docs 
          FOLDER: docs
