name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: |
          npm install
          npx @docusaurus/init@next init docusaurus classic
          cd ./packages/vocality-core
          rm -rf ../../docusaurus/docs
          npm run docs
          cd ../../docusaurus
          rm sidebar.js 
          cp ./website/sidebars.js ./
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docusaurus/build
